### ISSUE TITLE
Same Google Account can't be linked with multiple meteor accounts

### ISSUE THREAD

**Issue by thecoolelvin** [Meteor-Community-Packages/meteor-link-accounts#102]
When we have linked one google account with Meteor.linkWithGoogle() util function to some meteor user then if i login from another meteor user account and try to login with same google account. then it says 

`Provided google account is already in use by other user`

**Comment by StorytellerCZ** [comment]
This is not a bug, this is the intended behavior. These links are intended for logins, so if you have one Google account linked to 2+ account, how can we determine which account do you actually want to login to.

**Comment by thecoolelvin** [comment]
@StorytellerCZ  let's say 

We have a web application for Marketing Analysis.
and we have two Meteor users from same organisation (1 is from Accounts and 2 is from Admin department)

and we only have one google analytics account at all

So Now what happen if our account person had logged in via google. and with same google account our admin department person can not login because it says the Google account is already logged in with another meteor account.

Which doesn't make sense to me.

**Comment by StorytellerCZ** [comment]
Well first of, I think you are using organizations for what ever you are doing on Google. Each individual user then should have their own Google login. If that is the case then this isn't a problem as each person has their own Google login.

But if you create a special Google account that all the users login to access the Google service, then that is still considered in the eyes of the system as its own person/login. Say if you then in the system link two accounts to this one special Google account. Now your marketer goes and clicks on the login. Now Meteor goes and finds two accounts that are linked to this Google login. Now, how the hell does Meteor decide which user it should log into? It can't. You would have to give the user a selection of accounts to choose from that they want to log into. Currently I think Meteor just finds the first matching account and works with that, so even if you managed to do that you would end up with a situation where both the admin and marketer would end up in the same account.

Accounts always have to be mapped 1 to 1 (service to your app). If you need 1 to n then I'm guessing that you are interested in accessing Google's API and even then you should mirror Google's setup to a certain degree. If you still insist on 1 to n, then you do it outside of the accounts system as what you are doing is not related to the accounts system.

**Comment by thecoolelvin** [comment]
Okay @StorytellerCZ 
Thanks for explaining Meteor Accounts behaviour.
