### ISSUE TITLE
Accounts.registerLoginHandler issues with Meteor3

### ISSUE THREAD

**Issue by corentinleo** [Meteor-Community-Packages/meteor-link-accounts#114]
Hi,

I think there are small issues with Accounts.registerLoginHandler,

First you are using Meteor.user server side instead of Meteor.userAsync. Do I miss something ?

In Accounts._beforeLink if you don't await callback we won't be able to use asynchronous callback.

Best Regards

**Comment by StorytellerCZ** [comment]
I think, I got it. I think I will release a beta for Meteor 3.0-beta.0 soon.

**Comment by acemtp** [comment]
hey @StorytellerCZ I think you could merge the branch to main and publish the package?

**Comment by StorytellerCZ** [comment]
@acemtp yes, I will release RC.0 soon.

**Comment by acemtp** [comment]
just tested v3.0.0-rc.0 and it works fine for me!
thanks
