### ISSUE TITLE
Cross-Origin-Opener-Policy policy would block the window.closed call.

### ISSUE THREAD

**Issue by allenfuller** [Meteor-Community-Packages/meteor-link-accounts#117]
I am experiencing an issue completing the oAuth account process. After confirming the oAuth connection via a service, the pop-up closes, but the link is not added. I have 6 entries in the console for:
```
oauth_browser.js:25 Cross-Origin-Opener-Policy policy would block the window.closed call.
```

Has anyone else experienced this issue?

It appears there's an issue with `` in the util package (Meteor issue [#11363](https://github.com/meteor/meteor/issues/11363)), but I don't know where to add the `WebApp.connectHandlers.use`. Would that be in a startup file?

Thanks for any advice!

**Comment by allenfuller** [comment]
Update: This bug happens specifically with Google, however in general the popup does not close after confirming the connection.

**Comment by allenfuller** [comment]
Actually, it appears this whole thing is related to Meteor oAuth, or even Chrome, so I'm closing this one. However, if anyone has dealt with the popup not closing, I'd love your feedback.

**Comment by StorytellerCZ** [comment]
Yes, this is potentially a Meteor bug if you have too strict content policy. Best to open an issue on the Meteor repo to see if we can find a workaround.
