### ISSUE TITLE
Add onLink hook similar to Meteor's onLogin

### ISSUE THREAD

**Issue by redwraith2** [Meteor-Community-Packages/meteor-link-accounts#16]
I use Meteor's onLogin to grab a list of Facebook and Instagram friends. I know it's not strictly necessary, but it would be a very nice feature to have a server-side onLink hook so I can make API calls this way.

**Comment by yubozhao** [comment]
Hey @davidjaenisch Sorry to reply your issue so late.  I will see what I can do with this and hopefully, will get it into the next release.  Thank you for the suggestions

**Comment by kieckhafer** [comment]
Very late to the party here... was this ever added?

**Comment by StorytellerCZ** [comment]
@kieckhafer Not yet
