### ISSUE TITLE
Add server-side callback

### ISSUE THREAD

**Issue by lorensr** [Meteor-Community-Packages/meteor-link-accounts#3]
It would be useful to be able to do something like

``` coffeescript
Meteor.afterLinkUser (user) ->
  #push user.services.facebook.email onto user.emails
```

Rather than what I'm currently doing, which is `Meteor.call`ing an `afterLinkUser` method from the `linkWithFacebook` success callback client-side. My current method takes time - a round-trip to the client - and may not happen if something goes wrong on the client end or to the connection between server and client.

**Comment by caio-ribeiro-pereira** [comment]
If you use `meteor-accounts-meld` (https://github.com/splendido/meteor-accounts-meld) you can use this callback which works very well:

``` javascript
AccountsMeld.configure({
    serviceAddedCallback: function(userId, serviceAddedName) {
       // do something to update your collections with a new service added...
    }
});
```

**Comment by StorytellerCZ** [comment]
This hook will be `Accounts.afterLink` and will be part of the 2.2 release.
