### ISSUE TITLE
LinkedIn is not defined

### ISSUE THREAD

**Issue by JohanTh** [Meteor-Community-Packages/meteor-link-accounts#37]
Getting the following error when trying to sign in with LinkedIn:

> Uncaught ReferenceError: LinkedIn is not defined @linkedin.js:16

packages:

> jonperl:accounts-linkedin@1.1.0
> jonperl:linkedin@1.1.0
> bozhao:link-accounts@1.1.18

js:

``` javascript
Meteor.linkWithLinkedIn();
```

Have I missed anything? Would `bozhao:link-accounts` need an `api.use()` to get access to the exported vars such as `LinkedIn` from `jonperl:linkedin` or make use of `Package[]`?

To evade this error I did this on the client:

``` javascript
Meteor.linkWithLinkedIn = function (options, callback) {
  ...

  var credentialRequestCompleteCallback = Accounts.oauth.linkCredentialRequestCompleteHandler(callback);
  Package['jonperl:linkedin'].LinkedIn.requestCredential(options, credentialRequestCompleteCallback);
};
```

**Comment by MeKarina** [comment]
i could confirm i had the same issue and solution from @JohanTh works for me as well...

thank You..

**Comment by delgermurun** [comment]
Add only `jonperl:linkedin` package directly, not `jonperl:accounts-linkedin`.

**Comment by StorytellerCZ** [comment]
@JohanTh @delgermurun If you could identify where the issue is in the code a PR would be much appreciated. If there is not an issue, maybe a note in the README to the appropriate package should suffice.
