### ISSUE TITLE
If the the same service is already linked to another user, linking dies silently

### ISSUE THREAD

**Issue by ipstas** [Meteor-Community-Packages/meteor-link-accounts#49]
If the same account (same username from twitter) linked to another user, there is no error in server console or client. 

The only evidence I have in kadira from Error: [This social account is already in use by other user]
    at packages/bozhao_link-accounts/link_accounts_server.js:56:1

And since the popup window is closed momentarily, user believes account should be linked, but it is not happening

**Comment by yubozhao** [comment]
I will throw an error out in the next version, you will have to catch it on the server side

**Comment by ttacon** [comment]
There are certain situations in which we may want to allow multiple users to link with the same social account (i.e. multiple users posting from the same twitter account). What is your feeling about allowing this behaviour? Perhaps one could provide a whitelist of services for which this is allowed (thus ensuring we only allow this "double-linking" behaviour for accounts we expect it to occur on)?

**Comment by yubozhao** [comment]
@ttacon. Yep. There is that case as well.  Link different accounts from same service to meteor is not hard. But I have to make sure the login will works correctly. 

As of now, we get a free login with different services.

I.e. (Twitter A, Facebook A) can both login to same account. 


(Twitter A, Twitter B, Facebook A) Both Twitter account would have issue now. 

Let me know what you think.  
(Typing this during morning commute, so might not make much sense)

**Comment by ttacon** [comment]
Haha, no worries! I entirely agree, so what about the following:

1) We can provide a whitelist of services that know that they can allow linking multiple users to the same info.

2) Otherwise emit a more specific error message on a duplicate linking attempt.

Thoughts?

**Comment by yubozhao** [comment]
I think those are good ideas.  

Let me sink in idea 1 for a bit. Since right now. This is almost "invisible" package in the sense of application developer doesn't have to config anything. 

As far as number 2. I will work on it this weekend.

**Comment by adamwan92** [comment]
Is the error being implemented? Would be quite helpful so we can just render a popup that says "This app has already been linked with another account". Otherwise it causes a bit of confusion

**Comment by yubozhao** [comment]
@adamwan92 I haven't have enough free time to work on it, will try to get it done over July 4th.

**Comment by adamwan92** [comment]
For those who are facing the same problem, I found a quick fix.

```
  linkGoogle(){
    var self = this;
    Meteor.linkWithGoogle({}, function (err,res) {
      if (Meteor.user().services.google){
        // code for if successful
      } else {
        // error message goes here
      }
    });

  }
```

So after the Meteor.linkWithGoogle call is completed, it'll check if the user is linked with Google by checking if Meteor.user().services.google exists.

**Comment by StorytellerCZ** [comment]
Scheduling this for v2.3
