### ISSUE TITLE
Possible to store key on document other than Meter.user?

### ISSUE THREAD

**Issue by acomito** [Meteor-Community-Packages/meteor-link-accounts#52]
I have a collection of organizations. I'd like to allow them to connect their facebook/twitter/etc. pages. Can I leverage this or should I be looking elsewhere?

**Comment by shacks** [comment]
This is possibly not the best solution, but you could create a cron job to export data from one collection the another.

**Comment by StorytellerCZ** [comment]
Late, but better then never:
Yes, though not in a way you think. You connect to personal accounts. In those connections you would have to get permissions to manage groups/pages/organizations that the user has admin rights on that social network. With connecting the personal account (with the proper permissions) you gain access to the list of organizations and associated actions. Please see the API of the services you want to use for more information.
