### ISSUE TITLE
Before mergin callback

### ISSUE THREAD

**Issue by JefferyHus** [Meteor-Community-Packages/meteor-link-accounts#60]
Hi, the issue is that when the user logs in with gmail for example then logs out, the next time he will pick another service like facebook but this time he will try and merge google account with the current logged in, there will be an error as an already account exists with the same service id, so if possible to add a hook just before the merging process that will receive as params (oldId, newId) [accounts ids], so that I can do what I want with the old account (remove, update it).
My solution for another package was working great but the package is no longer updated.

**Comment by StorytellerCZ** [comment]
The user creates account1 which is linked to FB. Then logs out and creates account2 which is created via Google. Now the user wants to link account2 to their FB account as well, but that link has already been made to account1, so they can't.
Did I get that rights?

The easiest solution is for the user to unlink FB from account1 and then link it again at account2.

I think it might be easier to figure out how to work more easily with account merging packages on this than adding that entire functionality.

**Comment by StorytellerCZ** [comment]
Isn't this similar to #49 ?

**Comment by JefferyHus** [comment]
this has been 2 years, why github says 2017 ? :'( It started to collapse (joke).  And yes this question was about linking accounts after login out and trying to log in using another social network.
