### ISSUE TITLE
Move package under Meteor Community

### ISSUE THREAD

**Issue by StorytellerCZ** [Meteor-Community-Packages/meteor-link-accounts#80]
Me and @copleykj have started a group for important Meteor packages that are not much maintained lately and I would like to move this package there as I think it is very important and our desire is to at least merge any PRs and where there is an interest help people to actively develop packages.
https://github.com/Meteor-Community-Packages

Could we make this happen @yubozhao ?

**Comment by yubozhao** [comment]
@StorytellerCZ Yeah man, for sure.  Let me know what I need to do for this process.

**Comment by StorytellerCZ** [comment]
@yubozhao It seems that there are now multiple efforts underway. I'll wait few days to let the dust settle and then I will reach out to you so that we can get this into what ever the community decides on.

**Comment by yubozhao** [comment]
Sounds great!  Thank you for continue on keep the community active!  I wish I have another chance to use Meteor again.  It might not the best for everything, but I think for some applications, it still kick ass

**Comment by StorytellerCZ** [comment]
@yubozhao So the decisions have been made. I send you an invite into the community. You can move the repository there at your leisure. We'll figure the publishing automation soon after that.

**Comment by yubozhao** [comment]
Awesome.  Thank you @StorytellerCZ

**Comment by yubozhao** [comment]
@StorytellerCZ  moved
