### ISSUE TITLE
beforeLink hook does not work as expected

### ISSUE THREAD

**Issue by uuuJ** [Meteor-Community-Packages/meteor-link-accounts#96]
Hey there 👋, 

The beforeLink  hook [doc](https://github.com/Meteor-Community-Packages/meteor-link-accounts#accountsbeforelink) says it should be able to prevent linking depending of what it returns.

Even if I return false, true, or whatever in my hook, the `each` will ignore the result of the callback and `LinkUserFromExternalService ` will continue its execution and allow linking.
See that [block](https://github.com/Meteor-Community-Packages/meteor-link-accounts/blob/084faed249006aabf9455484103f3d27681a38ce/link_accounts_server.js#L95-L99)

I workarounded this problem by manually removing the connection in the `onLink` hook, but that's not very clean :(

**Comment by StorytellerCZ** [comment]
Hi @uuuJ 
Can you please check that #101 fixes the issue for you?

**Comment by corentinleo** [comment]
Hi 👋, 

I tried the same things as @uuuJ and return false in the Accounts.beforeLink seems to cancel the link but I'm facing another problem : 
When I return false I have the following meteor error : "A login handler should return a result or undefined".
So I tried to return undefined but same result.
I would like to know if I miss something or there is a problem with the code ? Thanks 🙏
