### ISSUE TITLE
wrong uppercase in the word linkedIn

### ISSUE THREAD

**Issue by ddaydd** [Meteor-Community-Packages/meteor-link-accounts#98]
Hello,

`Cannot read properties of undefined (reading 'requestCredential') at Object.Meteor.linkWithLinkedIn (linkedin.js:29)`

line 29
`Package['pauli:linkedin-oauth'].LinkedIn.requestCredential(options, credentialRequestCompleteCallback)`

but in pauli:linkedin-oauth , it's Linkedin not LinkedIn
`  api.export('Linkedin');`

thank you for correcting

**Comment by StorytellerCZ** [comment]
Will be released in v. 2.3.3
