### ISSUE TITLE
eslint-plugin-react doctrine error, babel-eslint package is deprecated

### ISSUE THREAD

**Issue by ddaydd** [Meteor-Community-Packages/meteor-link-accounts#99]
Hello,

i got this error when i deploy

`Error: chown /var/app/staging/programs/server/npm/node_modules/meteor/bozhao_link-accounts/node_modules/eslint-plugin-react/.node_modules-garbage-1aytbru.g2cd/doctrine: no such file or directory`

when I realized that the babel-eslint package is deprecated, I replaced it with @babel/eslint-parser in your package.json and now it works...

**Comment by StorytellerCZ** [comment]
Upgraded all dev dependencies.
